version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crypto_db
    restart: always
    environment:
      MYSQL_DATABASE: crypto_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7.2-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

  # Твій сайт (Scalable Web App)
  web:
    build: .
    # ПРИБРАЛИ 'container_name', щоб можна було запускати копії
    restart: always
    expose:
      - "8000" # Відкритий тільки для Nginx, не для людей
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_HOST: redis
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  # Балансувальник (Load Balancer)
  nginx:
    image: nginx:latest
    container_name: crypto_lb
    ports:
      - "80:80" # Вхідні двері для користувачів
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  worker:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_HOST: redis
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code
    command: ["python", "-u", "worker.py"]

volumes:
  db_data: