version: '3.8'

services:
  # 1. СЕРВІС БАЗИ ДАНИХ (DB)
  db:
    image: mysql:8.0
    container_name: crypto_db
    restart: always
    environment:
      MYSQL_DATABASE: crypto_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. СЕРВІС ЧЕРГИ (REDIS) - НОВИЙ КОМПОНЕНТ
  redis:
    image: redis:7.2-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"] # Не зберігаємо дані на диск для швидкості

  # 3. СЕРВІС САЙТУ (WEB)
  web:
    build: .
    container_name: crypto_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis: # ТЕПЕР САЙТ ЧЕКАЄ ЩЕ Й НА REDIS
        condition: service_started
    environment:
      # Встановлюємо URL для підключення до REDIS
      REDIS_HOST: redis
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code

volumes:
  db_data: