version: '3.8'

services:
  # 1. СЕРВІС БАЗИ ДАНИХ (DB)
  db:
    image: mysql:8.0
    container_name: crypto_db
    restart: always
    environment:
      MYSQL_DATABASE: crypto_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. СЕРВІС ЧЕРГИ (REDIS)
  redis:
    image: redis:7.2-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

  # 3. СЕРВІС САЙТУ (WEB - ПУБЛІКАТОР)
  web:
    build: .
    container_name: crypto_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_HOST: redis
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  # 4. СЕРВІС РОБІТНИКА (WORKER - СПОЖИВАЧ)
  worker:
    build: .
    container_name: crypto_worker_1 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_HOST: redis
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code
    command: ["python", "worker.py"] 

# ОГОЛОШЕННЯ VOLUMES (БЕЗ ЖОДНОГО ВІДСТУПУ)
volumes:
  db_data: