version: '3.8'

services:
  # Наша база даних
  db:
    image: mysql:8.0
    container_name: crypto_db
    restart: always
    environment:
      MYSQL_DATABASE: crypto_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Перевірка здоров'я бази (щоб сайт знав, коли вона готова)
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Наш Python сайт (тепер у контейнері!)
  web:
    build: .
    container_name: crypto_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Важливо: всередині докера адреса бази не 127.0.0.1, а ім'я сервісу "db"
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crypto_exchange
    volumes:
      - .:/code  # Щоб ми могли змінювати код на льоту

volumes:
  db_data: